name: Build WLED with custom usermods

on:
  workflow_dispatch:    # запуск вручную через кнопку

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install PlatformIO
        run: |
          pip install platformio

      - name: Install dependencies and build web UI
        run: |
          npm install
          npm run build

      - name: Build firmware
        run: |
          pio run -e custom_build

      - name: Upload firmware artifact
        uses: actions/upload-artifact@v4
        with:
          name: WLED-firmware
          path: .pio/build/custom_build/firmware.bin
